name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: |
          echo ${{ github.event.client_payload.sha }}
          echo ${{ github.event.client_payload.action }}
          echo ${{ github.event.client_payload.workflow }}
          echo ${{ github.event.client_payload.sender }}
          echo ${{ github.event.client_payload.message }}